--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/fernanACM/EnderChest
build-by-default: true
branches:
- PM4
projects:
  EnderChest:
    path: ""
    icon: icon-enderchest.png
    libs:
      - src: CortexPE/Commando/Commando
        version:  ^3.0.0
        branch: PM4
      - src: muqsit/simplepackethandler/SimplePacketHandler
        version: ^0.0.1
      - src: muqsit/InvMenu/InvMenu
        version: ^4.3.8
        branch: "4.0"
    lint:
      phpstan: false
...
