name: EnderChest
main: fernanACM\EnderChest\Ender
version: 2.0.1
api: 5.3.0
author: fernanACM
description: Portable EnderChest for PocketMine-MP 4.0 Servers
website: https://github.com/fernanACM

permissions:
  enderchest.acm:
    default: op
    description: Open enderchest /ec, /ender, /enderchest
